version: '3.7'

services:
  site:
    build: .deployment
    container_name: app
    ports:
      - 8000:80
      - 8443:443
    tty: true
    volumes:
      - .:/var/www/app-4bb61698
    networks:
      - laravel
  db:
    container_name: 'mysql'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes:
      - .deployment/db:/var/lib/mysql
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
