version: '3.7'

services:
  site:
    build: .deployment
    container_name: stage
    ports:
      - 8000:80
      - 8443:443
    tty: true
    volumes:
      - .:/var/www/app-4bb61698
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
